name: analizador de archivos

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  analyze-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: check files
        run: ls
